const { reduceMap } = require('../utils')
const chainlist = require('../providers/chainlist')
const defillama = require('../providers/defillama')
const Coin = require('../db/models/Coin')

class ChainlistSyncer {
  constructor() {
    this.chainIds = {
      1: 'ethereum',
      2: 'expanse',
      7: { name: 'ThaiChain', shortName: 'tch' },
      8: 'ubiq',
      10: 'optimism',
      11: { name: 'Metadium Mainnet', shortName: 'meta' },
      14: { name: 'Flare Mainnet', shortName: 'flr' },
      15: { name: 'Diode Prenet', shortName: 'diode' },
      17: { name: 'ThaiChain 2.0 ThaiFi', shortName: 'tfi' },
      19: 'songbird',
      20: 'elastos',
      22: { name: 'ELA-DID-Sidechain Mainnet', shortName: 'eladid' },
      24: 'kardiachain',
      25: 'crypto-com-chain',
      27: { name: 'ShibaChain', shortName: 'shib' },
      29: { name: 'Genesis L1', shortName: 'L1' },
      30: 'rootstock',
      33: { name: 'GoodData Mainnet', shortName: 'GooD' },
      35: { name: 'TBWG Chain', shortName: 'tbwg' },
      36: { name: 'Dxchain Mainnet', shortName: 'dx' },
      37: { name: 'SeedCoin-Network', shortName: 'SEED' },
      38: 'radium',
      40: 'telos',
      44: { name: 'Darwinia Crab Network', shortName: 'crab' },
      46: { name: 'Darwinia Network', shortName: 'darwinia' },
      48: { name: 'Ennothem Mainnet Proterozoic', shortName: 'etmp' },
      50: 'xdc',
      51: { name: 'XDC Apothem Network', shortName: 'txdc' },
      52: 'coinex-token',
      54: { name: 'Openpiece Mainnet', shortName: 'OP' },
      55: 'zyx',
      56: 'binancecoin',
      57: 'syscoin',
      58: { name: 'Ontology Mainnet', shortName: 'OntologyMainnet' },
      59: { name: 'EOS Mainnet', shortName: 'EOSMainnet' },
      60: 'gochain',
      61: 'ethereum-classic',
      64: { name: 'Ellaism', shortName: 'ellaism' },
      66: 'oec-token',
      68: { name: 'SoterOne Mainnet', shortName: 'SO1' },
      70: 'hoo-token',
      73: { name: 'FNCY', shortName: 'FNCY' },
      74: { name: 'IDChain Mainnet', shortName: 'idchain' },
      75: { name: 'Decimal Smart Chain Mainnet', shortName: 'DSC' },
      76: { name: 'Mix', shortName: 'mix' },
      77: { name: 'POA Network Sokol', shortName: 'spoa' },
      78: { name: 'PrimusChain mainnet', shortName: 'primuschain' },
      79: { name: 'Zenith Mainnet', shortName: 'zenith' },
      80: { name: 'GeneChain', shortName: 'GeneChain' },
      82: 'meter',
      86: { name: 'GateChain Mainnet', shortName: 'gt' },
      87: 'supernova',
      88: 'tomochain',
      90: { name: 'Garizon Stage0', shortName: 'gar-s0' },
      91: { name: 'Garizon Stage1', shortName: 'gar-s1' },
      92: { name: 'Garizon Stage2', shortName: 'gar-s2' },
      93: { name: 'Garizon Stage3', shortName: 'gar-s3' },
      96: { name: 'NEXT Smart Chain', shortName: 'nsc' },
      99: 'poa-network',
      100: 'gnosis',
      101: 'etherinc',
      106: 'velas',
      108: 'thunder-token',
      111: { name: 'EtherLite Chain', shortName: 'ETL' },
      113: { name: 'Dehvo', shortName: 'deh' },
      116: { name: 'DeBank Mainnet', shortName: 'debank-mainnet' },
      122: 'fuse-network-token',
      123: { name: 'Fuse Sparknet', shortName: 'spark' },
      124: { name: 'Decentralized Web Mainnet', shortName: 'dwu' },
      126: { name: 'OYchain Mainnet', shortName: 'OYchainMainnet' },
      127: { name: 'Factory 127 Mainnet', shortName: 'feth' },
      128: 'huobi-token',
      137: 'matic-network',
      142: { name: 'DAX CHAIN', shortName: 'dax' },
      144: { name: 'PHI Network v2', shortName: 'PHI' },
      163: 'lightstreams',
      168: { name: 'AIOZ Network', shortName: 'aioz' },
      180: { name: 'AME Chain Mainnet', shortName: 'ame' },
      186: { name: 'Seele Mainnet', shortName: 'Seele' },
      188: { name: 'BMC Mainnet', shortName: 'BMC' },
      193: { name: 'Crypto Emergency', shortName: 'cem' },
      199: { name: 'BitTorrent Chain Mainnet', shortName: 'BTT' },
      200: 'xdaiarb',
      211: { name: 'Freight Trust Network', shortName: 'EDI' },
      217: { name: 'SiriusNet V2', shortName: 'SIN2' },
      218: { name: 'SoterOne Mainnet old', shortName: 'SO1-old' },
      222: { name: 'Permission', shortName: 'ASK' },
      225: { name: 'LACHAIN Mainnet', shortName: 'LA' },
      246: 'energy-web-token',
      248: { name: 'Oasys Mainnet', shortName: 'OAS' },
      250: 'fantom',
      258: { name: 'Setheum', shortName: 'setm' },
      262: { name: 'SUR Blockchain Network', shortName: 'SUR' },
      269: 'high-performance-blockchain',
      288: 'boba-network',
      300: { name: 'Optimism on Gnosis', shortName: 'ogc' },
      301: { name: 'Bobaopera', shortName: 'Bobaopera' },
      314: { name: 'Filecoin - Mainnet', shortName: 'filecoin' },
      321: 'kucoin-shares',
      324: { name: 'zkSync v2', shortName: 'zksync' },
      333: { name: 'Web3Q Mainnet', shortName: 'w3q' },
      336: 'shiden',
      361: 'theta-token',
      369: { name: 'PulseChain Mainnet', shortName: 'pls' },
      385: { name: 'Lisinski', shortName: 'lisinski' },
      416: 'sx',
      427: { name: 'Zeeth Chain', shortName: 'zeeth' },
      499: { name: 'Rupaya', shortName: 'rupx' },
      500: { name: 'Camino C-Chain', shortName: 'Camino' },
      512: { name: 'Double-A Chain Mainnet', shortName: 'aac' },
      516: { name: 'Gear Zero Network Mainnet', shortName: 'gz-mainnet' },
      520: { name: 'XT Smart Chain Mainnet', shortName: 'xt' },
      529: { name: 'Firechain Mainnet', shortName: 'fire' },
      530: { name: 'F(x)Core Mainnet Network', shortName: 'FxCore' },
      534: 'candle',
      555: { name: 'Vela1 Chain Mainnet', shortName: 'CLASS' },
      558: { name: 'Tao Network', shortName: 'tao' },
      592: 'astar',
      686: 'karura',
      707: { name: 'BlockChain Station Mainnet', shortName: 'bcs' },
      721: { name: 'Lycan Chain', shortName: 'LYC' },
      766: { name: 'QL1', shortName: 'qom' },
      777: { name: 'cheapETH', shortName: 'cth' },
      787: { name: 'Acala Network', shortName: 'aca' },
      800: { name: 'Lucid Blockchain', shortName: 'LUCID' },
      803: { name: 'Haic', shortName: 'haic' },
      813: { name: 'Qitmeer', shortName: 'meer' },
      820: 'callisto',
      841: { name: 'Taraxa Mainnet', shortName: 'tara' },
      859: { name: 'Zeeth Chain Dev', shortName: 'zeethdev' },
      877: { name: 'Dexit Network', shortName: 'DXT' },
      880: { name: 'Ambros Chain Mainnet', shortName: 'ambros' },
      888: 'wanchain',
      909: { name: 'Portal Fantasy Chain', shortName: 'PF' },
      970: { name: 'Oort Mainnet', shortName: 'ccn' },
      971: { name: 'Oort Huygens', shortName: 'Huygens' },
      972: { name: 'Oort Ascraeus', shortName: 'Ascraeus' },
      977: { name: 'Nepal Blockchain Network', shortName: 'yeti' },
      980: { name: 'TOP Mainnet EVM', shortName: 'top_evm' },
      985: { name: 'Memo Smart Chain Mainnet', shortName: 'memochain' },
      989: { name: 'TOP Mainnet', shortName: 'top' },
      998: 'link',
      1000: { name: 'GTON Mainnet', shortName: 'gton' },
      1008: { name: 'Eurus Mainnet', shortName: 'eun' },
      1010: 'evrice',
      1012: 'newton-project',
      1022: 'sakura',
      1024: { name: 'CLV Parachain', shortName: 'clv' },
      1030: 'conflux-token',
      1039: { name: 'Bronos Mainnet', shortName: 'bronos-mainnet' },
      1088: 'metis-token',
      1099: { name: 'MOAC mainnet', shortName: 'moac' },
      1111: { name: 'WEMIX3.0 Mainnet', shortName: 'wemix' },
      1130: 'defichain',
      1139: { name: 'MathChain', shortName: 'MATH' },
      1197: { name: 'Iora Chain', shortName: 'iora' },
      1202: { name: 'World Trade Technical Chain Mainnet', shortName: 'wtt' },
      1213: { name: 'Popcateum Mainnet', shortName: 'popcat' },
      1214: { name: 'EnterChain Mainnet', shortName: 'enter' },
      1229: { name: 'Exzo Network Mainnet', shortName: 'xzo' },
      1231: 'ultron',
      1234: 'step',
      1246: { name: 'OM Platform Mainnet', shortName: 'om' },
      1280: { name: 'HALO Mainnet', shortName: 'HO' },
      1284: 'moonbeam',
      1285: 'moonriver',
      1286: { name: 'Moonrock old', shortName: 'mrock-old' },
      1287: { name: 'Moonbase Alpha', shortName: 'mbase' },
      1288: { name: 'Moonrock', shortName: 'mrock' },
      1294: { name: 'Bobabeam', shortName: 'Bobabeam' },
      1311: { name: 'Dos Fuji Subnet', shortName: 'DOS' },
      1314: { name: 'Alyx Mainnet', shortName: 'alyx' },
      1319: { name: 'Aitd Mainnet', shortName: 'aitd' },
      1353: { name: 'CIC Chain Mainnet', shortName: 'CIC' },
      1455: { name: 'Ctex Scan Blockchain', shortName: 'CTEX' },
      1506: { name: 'Sherpax Mainnet', shortName: 'Sherpax' },
      1515: { name: 'Beagle Messaging Chain', shortName: 'beagle' },
      1618: { name: 'Catecoin Chain Mainnet', shortName: 'cate' },
      1620: 'atheios',
      1657: 'bata',
      1688: { name: 'LUDAN Mainnet', shortName: 'LUDAN' },
      1701: { name: 'Anytype EVM Chain', shortName: 'AnytypeChain' },
      1707: { name: 'TBSI Mainnet', shortName: 'TBSI' },
      1818: 'cube-network',
      1856: 'teslafunds',
      1898: { name: 'BON Network', shortName: 'boya' },
      1951: { name: 'D-Chain Mainnet', shortName: 'dchain-mainnet' },
      1975: { name: 'ONUS Chain Mainnet', shortName: 'onus-mainnet' },
      1987: 'ethergem',
      1994: { name: 'Ekta', shortName: 'ekta' },
      2000: 'dogechain',
      2001: { name: 'Milkomeda C1 Mainnet', shortName: 'milkAda' },
      2002: { name: 'Milkomeda A1 Mainnet', shortName: 'milkALGO' },
      2009: { name: 'CloudWalk Mainnet', shortName: 'cloudwalk_mainnet' },
      2016: { name: 'MainnetZ Mainnet', shortName: 'NetZm' },
      2020: { name: 'PublicMint Mainnet', shortName: 'pmint' },
      2021: { name: 'Edgeware Mainnet', shortName: 'edg' },
      2025: { name: 'Rangers Protocol Mainnet', shortName: 'rpg' },
      2043: { name: 'OriginTrail Parachain', shortName: 'otp' },
      2077: { name: 'Quokkacoin Mainnet', shortName: 'QKA' },
      2100: { name: 'Ecoball Mainnet', shortName: 'eco' },
      2109: { name: 'Exosama Network', shortName: 'exn' },
      2151: { name: 'BOSagora Mainnet', shortName: 'boa' },
      2152: 'findora',
      2154: { name: 'Findora Forge', shortName: 'findora-forge' },
      2203: { name: 'Bitcoin EVM', shortName: 'eBTC' },
      2213: { name: 'Evanesco Mainnet', shortName: 'evanesco' },
      2222: 'kava',
      2223: { name: 'VChain Mainnet', shortName: 'VChain' },
      2300: { name: 'BOMB Chain', shortName: 'bomb' },
      2330: { name: 'Altcoinchain', shortName: 'alt' },
      2559: { name: 'Kortho Mainnet', shortName: 'ktoc' },
      2569: { name: 'TechPay Mainnet', shortName: 'tpc' },
      2606: { name: 'PoCRNet', shortName: 'pocrnet' },
      2611: { name: 'Redlight Chain Mainnet', shortName: 'REDLC' },
      2612: { name: 'EZChain C-Chain Mainnet', shortName: 'EZChain' },
      2999: { name: 'BitYuan Mainnet', shortName: 'bty' },
      3000: { name: 'CENNZnet Rata', shortName: 'cennz-r' },
      3001: { name: 'CENNZnet Nikau', shortName: 'cennz-n' },
      3031: { name: 'Orlando Chain', shortName: 'ORL' },
      3334: { name: 'Web3Q Galileo', shortName: 'w3q-g' },
      3400: { name: 'Paribu Net Mainnet', shortName: 'prb' },
      3501: { name: 'JFIN Chain', shortName: 'jfin' },
      3601: { name: 'PandoProject Mainnet', shortName: 'pando-mainnet' },
      3666: { name: 'Metacodechain', shortName: 'metacode' },
      3690: 'bitcore',
      3737: { name: 'Crossbell', shortName: 'csb' },
      3912: { name: 'DRAC Network', shortName: 'drac' },
      3966: { name: 'DYNO Mainnet', shortName: 'dyno' },
      3999: { name: 'YuanChain Mainnet', shortName: 'ycc' },
      4181: { name: 'PHI Network V1', shortName: 'PHIv1' },
      4444: 'htmlcoin',
      4689: 'iotex',
      4919: { name: 'Venidium Mainnet', shortName: 'xvm' },
      5000: { name: 'Mantle', shortName: 'mantle' },
      5177: { name: 'TLChain Network Mainnet', shortName: 'tlc' },
      5197: { name: 'EraSwap Mainnet', shortName: 'es' },
      5234: { name: 'Humanode Mainnet', shortName: 'hmnd' },
      5290: { name: 'Firechain Mainnet Old', shortName: '_old_fire' },
      5315: { name: 'Uzmi Network Mainnet', shortName: 'UZMI' },
      5551: 'nahmii',
      5555: { name: 'Chain Verse Mainnet', shortName: 'cverse' },
      5869: { name: 'Wegochain Rubidium Mainnet', shortName: 'rbd' },
      6066: { name: 'Tres Mainnet', shortName: 'TRESMAIN' },
      6626: { name: 'Pixie Chain Mainnet', shortName: 'pixie-chain' },
      6789: { name: 'Gold Smart Chain Mainnet', shortName: 'STANDm' },
      6969: 'tombchain',
      6999: { name: 'PolySmartChain', shortName: 'psc' },
      7000: { name: 'ZetaChain Mainnet', shortName: 'zetachain-mainnet' },
      7027: { name: 'Ella the heart', shortName: 'ELLA' },
      7070: { name: 'Planq Mainnet', shortName: 'planq' },
      7341: { name: 'Shyft Mainnet', shortName: 'shyft' },
      7700: 'canto',
      8000: { name: 'Teleport', shortName: 'teleport' },
      8080: { name: 'Shardeum Liberty 1.X', shortName: 'Liberty10' },
      8081: { name: 'Shardeum Liberty 2.X', shortName: 'Liberty20' },
      8098: { name: 'StreamuX Blockchain', shortName: 'StreamuX' },
      8217: 'klay-token',
      8654: { name: 'Toki Network', shortName: 'toki' },
      8723: { name: 'TOOL Global Mainnet', shortName: 'olo' },
      8738: { name: 'Alph Network', shortName: 'alph' },
      8880: { name: 'Unique', shortName: 'unq' },
      8881: { name: 'Quartz by Unique', shortName: 'qtz' },
      8883: { name: 'Sapphire by Unique', shortName: 'sph' },
      8888: { name: 'XANAChain', shortName: 'XANAChain' },
      8889: { name: 'Vyvo Smart Chain', shortName: 'vsc' },
      8898: 'moments',
      8899: { name: 'JIBCHAIN L1', shortName: 'jbc' },
      8989: { name: 'Giant Mammoth Mainnet', shortName: 'gmmt' },
      8995: { name: 'bloxberg', shortName: 'berg' },
      9001: 'evmos',
      9012: { name: 'BerylBit Mainnet', shortName: 'brb' },
      9100: { name: 'Genesis Coin', shortName: 'GENEC' },
      9700: { name: 'Oort MainnetDev', shortName: 'MainnetDev' },
      10000: 'bitcoin-cash',
      10024: { name: 'Gon Chain', shortName: 'gon' },
      10086: { name: 'SJATSH', shortName: 'SJ' },
      10101: { name: 'Blockchain Genesis Mainnet', shortName: 'GEN' },
      10248: { name: '0XTade', shortName: '0xt' },
      10507: { name: 'Numbers Mainnet', shortName: 'Jade' },
      10823: { name: 'CryptoCoinPay', shortName: 'CCP' },
      10946: { name: 'Quadrans Blockchain', shortName: 'quadrans' },
      11110: { name: 'Astra', shortName: 'astra' },
      11111: { name: 'WAGMI', shortName: 'WAGMI' },
      11235: { name: 'Haqq Network', shortName: 'ISLM' },
      11888: { name: 'SanR Chain', shortName: 'SAN' },
      12052: { name: 'Singularity ZERO Mainnet', shortName: 'ZERO' },
      13000: { name: 'SPS', shortName: 'SPS' },
      13308: 'credit',
      13381: { name: 'Phoenix Mainnet', shortName: 'Phoenix' },
      13812: { name: 'Susono', shortName: 'sus' },
      16000: { name: 'MetaDot Mainnet', shortName: 'mtt' },
      18159: { name: 'Proof Of Memes', shortName: 'pom' },
      19845: { name: 'BTCIX Network', shortName: 'btcix' },
      20736: { name: 'P12 Chain', shortName: 'p12' },
      21337: { name: 'CENNZnet Azalea', shortName: 'cennz-a' },
      21816: { name: 'omChain Mainnet', shortName: 'omc' },
      22023: { name: 'Taycan', shortName: 'SFL' },
      22776: { name: 'MAP Mainnet', shortName: 'map' },
      23294: { name: 'Oasis Sapphire', shortName: 'sapphire' },
      24484: { name: 'Webchain', shortName: 'web' },
      24734: 'webchain',
      25888: { name: 'Hammer Chain Mainnet', shortName: 'GOLDT' },
      26600: 'hertz-network',
      26863: { name: 'OasisChain Mainnet', shortName: 'OAC' },
      31102: { name: 'Ethersocial Network', shortName: 'esn' },
      31223: { name: 'CloudTx Mainnet', shortName: 'CLDTX' },
      32520: 'bitrise-token',
      32659: 'fsn',
      33333: { name: 'Aves Mainnet', shortName: 'avs' },
      35011: { name: 'J2O Taro', shortName: 'j2o' },
      35441: { name: 'Q Mainnet', shortName: 'q' },
      39797: { name: 'Energi Mainnet', shortName: 'nrg' },
      39815: 'oho',
      41500: { name: 'Opulent-X BETA', shortName: 'ox-beta' },
      42069: { name: 'pegglecoin', shortName: 'PC' },
      42161: 'arbitrum',
      42170: 'arb-nova',
      42220: 'celo',
      42262: 'oasis-network',
      43110: { name: 'Athereum', shortName: 'avaeth' },
      43114: 'avalanche-2',
      43288: { name: 'Boba Avax', shortName: 'bobaavax' },
      45000: { name: 'Autobahn Network', shortName: 'AutobahnNetwork' },
      47805: 'rei-network',
      51712: { name: 'Sardis Mainnet', shortName: 'SRDXm' },
      53935: { name: 'DFK Chain', shortName: 'DFK' },
      55555: 'reichain',
      56288: { name: 'Boba BNB Mainnet', shortName: 'BobaBnb' },
      61803: { name: 'Etica Mainnet', shortName: 'Etica' },
      61916: { name: 'DoKEN Super Chain Mainnet', shortName: 'DoKEN' },
      62621: { name: 'MultiVAC Mainnet', shortName: 'mtv' },
      63000: { name: 'eCredits Mainnet', shortName: 'ecs' },
      67390: { name: 'SiriusNet', shortName: 'mcl' },
      70000: { name: 'Thinkium Mainnet Chain 0', shortName: 'TKM0' },
      70001: { name: 'Thinkium Mainnet Chain 1', shortName: 'TKM1' },
      70002: { name: 'Thinkium Mainnet Chain 2', shortName: 'TKM2' },
      70103: { name: 'Thinkium Mainnet Chain 103', shortName: 'TKM103' },
      71402: 'godwoken',
      73927: { name: 'Mixin Virtual Machine', shortName: 'mvm' },
      75000: { name: 'ResinCoin Mainnet', shortName: 'resin' },
      77612: { name: 'Vention Smart Chain Mainnet', shortName: 'vscm' },
      88888: { name: 'IVAR Chain Mainnet', shortName: 'ivar' },
      97288: { name: 'Boba BNB Mainnet Old', shortName: 'BobaBnbOld' },
      99999: { name: 'UB Smart Chain', shortName: 'usc' },
      100000: { name: 'QuarkChain Mainnet Root', shortName: 'qkc-r' },
      100001: { name: 'QuarkChain Mainnet Shard 0', shortName: 'qkc-s0' },
      100002: { name: 'QuarkChain Mainnet Shard 1', shortName: 'qkc-s1' },
      100003: { name: 'QuarkChain Mainnet Shard 2', shortName: 'qkc-s2' },
      100004: { name: 'QuarkChain Mainnet Shard 3', shortName: 'qkc-s3' },
      100005: { name: 'QuarkChain Mainnet Shard 4', shortName: 'qkc-s4' },
      100006: { name: 'QuarkChain Mainnet Shard 5', shortName: 'qkc-s5' },
      100007: { name: 'QuarkChain Mainnet Shard 6', shortName: 'qkc-s6' },
      100008: { name: 'QuarkChain Mainnet Shard 7', shortName: 'qkc-s7' },
      103090: { name: 'Crystaleum', shortName: 'CRFI' },
      108801: { name: 'BROChain Mainnet', shortName: 'bro' },
      131419: { name: 'ETND Chain Mainnets', shortName: 'ETND' },
      200625: 'akroma',
      201018: { name: 'Alaya Mainnet', shortName: 'alaya' },
      201804: { name: 'Mythical Chain', shortName: 'myth' },
      210425: { name: 'PlatON Mainnet', shortName: 'platon' },
      220315: { name: 'Mas Mainnet', shortName: 'mas' },
      246529: { name: 'ARTIS sigma1', shortName: 'ats' },
      256256: { name: 'CMP-Mainnet', shortName: 'cmp-mainnet' },
      281121: { name: 'Social Smart Chain Mainnet', shortName: 'SoChain' },
      333999: 'polis',
      381931: { name: 'Metal C-Chain', shortName: 'metal' },
      381932: { name: 'Metal Tahoe C-Chain', shortName: 'Tahoe' },
      420420: 'kekchain',
      432204: { name: 'Dexalot Subnet', shortName: 'dexalot' },
      474142: { name: 'OpenChain Mainnet', shortName: 'oc' },
      513100: { name: 'ethereum Fair', shortName: 'etf' },
      534352: { name: 'Scroll', shortName: 'scr' },
      641230: { name: 'Bear Network Chain Mainnet', shortName: 'BRNKC' },
      800001: { name: 'OctaSpace', shortName: 'octa' },
      846000: { name: '4GoodNetwork', shortName: 'bloqs4good' },
      888888: 'vision',
      900000: { name: 'Posichain Mainnet Shard 0', shortName: 'psc-s0' },
      955305: { name: 'Eluvio Content Fabric', shortName: 'elv' },
      1313114: { name: 'Etho Protocol', shortName: 'etho' },
      1313500: { name: 'Xerom', shortName: 'xero' },
      1337802: { name: 'Kiln', shortName: 'kiln' },
      2099156: { name: 'Plian Mainnet Main', shortName: 'plian-mainnet' },
      5555555: { name: 'Imversed Mainnet', shortName: 'imversed' },
      7355310: { name: 'OpenVessel', shortName: 'vsl' },
      7762959: { name: 'Musicoin', shortName: 'music' },
      8007736: { name: 'Plian Mainnet Subchain 1', shortName: 'plian-mainnet-l2' },
      10101010: { name: 'Soverun Mainnet', shortName: 'SVRNm' },
      13371337: { name: 'PepChain Churchill', shortName: 'tpep' },
      14288640: { name: 'Anduschain Mainnet', shortName: 'anduschain-mainnet' },
      18289463: { name: 'IOLite', shortName: 'ilt' },
      20180430: { name: 'SmartMesh Mainnet', shortName: 'spectrum' },
      20181205: { name: 'quarkblockchain', shortName: 'qki' },
      22052002: 'excelon',
      27082022: { name: 'Excoincial Chain Mainnet', shortName: 'exl' },
      28945486: { name: 'Auxilium Network Mainnet', shortName: 'auxi' },
      35855456: 'joys',
      61717561: { name: 'Aquachain', shortName: 'aqua' },
      192837465: { name: 'Gather Mainnet Network', shortName: 'GTH' },
      245022934: { name: 'Neon EVM MainNet', shortName: 'neonevm-mainnet' },
      311752642: { name: 'OneLedger Mainnet', shortName: 'oneledger' },
      503129905: { name: 'Nebula Staging', shortName: 'nebula-staging' },
      1122334455: { name: 'IPOS Network', shortName: 'ipos' },
      1313161554: 'aurora-near',
      1313161556: { name: 'Aurora Betanet', shortName: 'aurora-betanet' },
      1482601649: { name: 'Nebula Mainnet', shortName: 'nebula-mainnet' },
      1564830818: { name: 'Calypso NFT Hub (SKALE)', shortName: 'calypso-mainnet' },
      1666600000: 'harmony',
      1666600001: { name: 'Harmony Mainnet Shard 1', shortName: 'hmy-s1' },
      1666600002: { name: 'Harmony Mainnet Shard 2', shortName: 'hmy-s2' },
      1666600003: { name: 'Harmony Mainnet Shard 3', shortName: 'hmy-s3' },
      2021121117: { name: 'DataHopper', shortName: 'hop' },
      2046399126: { name: 'Europa SKALE Chain', shortName: 'europa' },
      3125659152: { name: 'Pirl', shortName: 'pirl' },
      11297108109: 'palm',
      197710212030: { name: 'Ntity Mainnet', shortName: 'ntt' },
      383414847825: { name: 'Zeniq', shortName: 'zeniq' },
      666301171999: { name: 'PDC Mainnet', shortName: 'ipdc' },
      6022140761023: { name: 'Molereum Network', shortName: 'mole' }
    }
  }

  async sync() {
    const llamaIds = reduceMap(await defillama.getChains(), 'chainId', 'gecko_id')

    const data = await chainlist.getChains()
    const chains = data.map(item => {
      return {
        ...item,
        isTestnet: this.isTestnet(item.name) || this.isTestnet(item.title) || this.isTestnet(item.network)
      }
    }).filter(i => !i.isTestnet)

    const map = {}
    for (let i = 0; i < chains.length; i += 1) {
      const chain = chains[i];
      const coins = await Coin.query(`
        select c.uid, p.chain_uid
         from coins c, platforms p where c.id = p.coin_id
          and (p.type = 'native' or p.type = c.uid)
          and c.code = lower('${chain.shortName}')
      `)

      let uid
      if (llamaIds[chain.chainId]) {
        uid = llamaIds[chain.chainId]
      } else if (coins[0]) {
        uid = coins[0].chain_uid
      } else {
        uid = { name: chain.name, shortName: chain.shortName }
      }

      map[chain.chainId] = uid
    }

    console.log(map)
  }

  isTestnet(string) {
    if (!string) return false
    const item = string.toLowerCase()
    return item.includes('test') || item.includes('devnet')
  }
}

module.exports = ChainlistSyncer
